[package]
name = "ai-honyaku-jimaku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tikv-client = "0.3.0"
# whisper-rs = "0.10.0"